-- SQL PROJECT
-- Grocery Store Management

-- creating database 
create database Grocecry_store;

-- using the database
use Grocecry_store;

-- Creating Tables
-- 1. Supplier Table
create table Supplier(
Supplier_id tinyint primary key,
Supplier_name varchar(200),
Address text
);
select * from Supplier;

-- 2.Categories Table
create table Categories(
Category_id tinyint primary key,
Category_name varchar(200)
);
select * from categories;

-- 3.Employees Table
create table employees(
 emp_id tinyint primary key,
 emp_name varchar(200),
 hire_date varchar(255)
);
select * from employees;

-- 4.Customers Table
create table  Customers(
 Customer_id smallint primary key,
 Customer_name varchar(200),
 Address text
 );
 select * from customers;
 
 -- 5.Products Table
create table products(
 product_id tinyint primary key,
 product_name varchar(200),
 supplier_id tinyint,
 category_id tinyint,
 price decimal(10,2),
 foreign key (supplier_id) references supplier(Supplier_id),
 foreign key (Category_id) references categories(category_id)
);
select * from products;

-- 6.Orders Table
create table Orders(
 order_id smallint primary key,
 customer_id smallint,
 emp_id tinyint,
 order_date varchar(200),
 foreign key (customer_id) references customers(customer_id),
 foreign key (emp_id) references employees(emp_id)
 );
 select * from orders;
 
-- 7. Order_Details Table
create table  order_details(
 order_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
 order_id SMALLINT,
 product_id TINYINT,
 quantity TINYINT,
 each_price DECIMAL(10,2),
 total_price DECIMAL(10,2),
 foreign key (order_id) references orders(order_id),
 foreign key (product_id) references products(product_id)
);
select * from order_details;

-- Analysis Questions


-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.
-- How many unique customers have placed orders?
select count(distinct(customer_id)) as unique_customers from orders;

-- Which customers have placed the highest number of orders?
select  c.customer_id,c.customer_name, count(o.order_id) as Number_of_orders from customers c  
join orders o on
o.customer_id=c.customer_id
group by c.customer_id,c.customer_name
order by Number_of_orders desc;

-- What is the total and average purchase value per customer?
select o.customer_id,c.customer_name,sum(od.total_price) as Total_purchase,
avg(od.total_price) as Avg_Purchase from orders o
join order_details od on 
o.order_id = od.order_id
join customers c on
c.customer_id = o.customer_id
group by o.customer_id,c.customer_name
order by Total_purchase desc;

-- Who are the top 5 customers by total purchase amount?
select o.customer_id,c.customer_name,sum(od.total_price) as Total_purchase from orders o
join order_details od on
o.order_id = od.order_id
join customers c on
c.customer_id = o.customer_id
group by o.customer_id,c.customer_name
order by Total_purchase desc limit 5;

-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.
-- How many products exist in each category?
select c.category_id,c.category_name,count(p.product_id) as number_of_products from products p
join categories c on
c.category_id = p.category_id
group by c.category_id,c.category_name;

-- What is the average price of products by category?
select c.category_name,avg(p.price) as Avg_price_of_products from categories c
join products p on
c.category_id = p.category_id
group by c.category_name;

-- Which products have the highest total sales volume (by quantity)?
select p.product_name,sum(od.quantity) as  highest_total_sales from order_details od
join products p on
p.product_id = od.product_id
group by p.product_name
order by highest_total_sales desc;

-- What is the total revenue generated by each product?
select p.product_name,sum(od.total_price) as total_revenue from order_details od
join products p on
p.product_id = od.product_id
group by p.product_name
order by total_revenue;

-- How do product sales vary by category and supplier?
select p.product_name,c.category_name,s.supplier_name,sum(od.total_price) as total_revenue,
sum(od.quantity) as total_quantity from order_details od
join products p on 
od.product_id = p.product_id
join categories c on
p.category_id = c.category_id
join supplier s on
p.supplier_id = s.supplier_id
group by p.product_name,c.category_name,s.supplier_name
order by c.category_name,total_revenue desc; 

-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.
-- How many orders have been placed in total?
select count(order_id) as total_orders from orders;

-- What is the average value per order?
select avg(order_total) as average_order_value from
(select order_id,sum(total_price) as  order_total from order_details
 group by  order_id
)as sub;

-- On which dates were the most orders placed?
select order_date,count(order_id) as number_of_orders from orders
group by order_date
order by number_of_orders desc;

-- What are the monthly trends in order volume and revenue?
select date_format(str_to_date(o.order_date,'%m/%d/%y'),'%m') as month,
count(distinct o.order_id) as order_volume ,
sum(od.total_price) as total_revenue from order_details od
join orders o on 
o.order_id = od.order_id
group by month
order by month;

-- How do order patterns vary across weekdays and weekends?
select 
case 
when dayofweek(str_to_date(order_date,'%m/%d/%y')) in (1,7) then "Weekend"
else "Weekday" 
end   as day_type,
count(order_id) as total_orders from orders
group by day_type;

-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.
-- How many suppliers are there in the database?
select count(supplier_id) as Number_of_suppliers from supplier;

-- Which supplier provides the most products?
select s.supplier_id,s.supplier_name,count(p.product_id) as number_of_products from supplier s
join products p on
p.supplier_id = s.supplier_id
group by s.supplier_id,s.supplier_name
order by number_of_products desc;

-- What is the average price of products from each supplier?
select s.supplier_id,s.supplier_name,avg(p.price) as Avg_of_products from supplier s
join products p on
p.supplier_id = s.supplier_id
group by s.supplier_id,s.supplier_name
order by Avg_of_products desc;

-- Which suppliers contribute the most to total product sales (by revenue)?
select s.supplier_id,s.supplier_name,sum(od.total_price) as total_revenue,
sum(od.quantity) as total_quantity from order_details od
join products p on
od.product_id = p.product_id
join supplier s on
p.supplier_id = s.supplier_id
group by  s.supplier_id,s.supplier_name
order by total_revenue desc;

-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.
-- How many employees have processed orders?
select count(distinct emp_id) as no_of_employees from orders;

-- Which employees have handled the most orders?
select e.emp_id,e.emp_name,count(o.order_id) as Number_of_orders from employees e
join orders o on
o.emp_id = e.emp_id
group by e.emp_id,e.emp_name
order by Number_of_orders desc;

-- What is the total sales value processed by each employee?
select e.emp_id,e.emp_name,sum(od.total_price) as total_sales_value from employees e
join orders o on 
o.emp_id = e.emp_id
join order_details od on
o.order_id = od.order_id
group by e.emp_id,e.emp_name
order by total_sales_value desc;

-- What is the average order value handled per employee?
select e.emp_id,e.emp_name,avg(order_total) as avg_order_value from employees e
join (
select 
o.emp_id,
o.order_id,
SUM(od.total_price) as order_total  from orders o
join order_details od 
on o.order_id = od.order_id
group by o.order_id, o.emp_id
) as sub 
  ON e.emp_id = sub.emp_id
group by e.emp_id,e.emp_name
order by  avg_order_value desc;

-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.
-- What is the relationship between quantity ordered and total.
select quantity,avg(total_price)avg_total_price from order_details
group by quantity
order by quantity;

-- What is the average quantity ordered per product?
select p.product_id,p.product_name,avg(od.quantity) as  average_quantity from  products p
join order_details od  on
p.product_id = od.product_id
group by   p.product_id,p.product_name
order by average_quantity desc ;

-- How does the unit price vary across products and orders?
select distinct p.product_id,p.product_name,od.each_price as unit_price from order_details od
join products p on
p.product_id = od.product_id
order by  p.product_id;